#!/bin/sh
#This pre-commit hook exports all the eagle boards to pdf and removes license info from the project file.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

       epfs=$(git diff --cached --name-only --diff-filter=ACMR $against|grep --color=never 'eagle/[^/]*epf$')
updatedpdfs=$(git diff --cached --name-only --diff-filter=ACMR $against|grep --color=never 'eagle/[^/]*brd\|sch$'|sed 's:eagle/\([^/]*\)$:\1.pdf:g')
removedpdfs=$(git diff --cached --name-only --diff-filter=D    $against|grep --color=never 'eagle/[^/]*brd\|sch$'|sed 's:eagle/\([^/]*\)$:\1.pdf:g')

#Remove serial info
for epf in $epfs
do
	sed -i 's/Serial=".*"//g' $epf
	git add $epf
done

cd eagle/pdf
unset GIT_DIR

if [ -n "$updatedpdfs" ]; then
	make $updatedpdfs
	git add -f *.pdf
fi
if [ -n "$removedpdfs" ]; then
	git rm $removedpdfs
fi

exit 0